language: go
go:
  - 1.7.x

sudo: required

services:
  - docker

env:

  global:
    - secure: "M+kBVKm38h6ATtURKbLUsG0HYcXjNFnG5m2x+yaUQIWC7wU3uzRmq/5KRiX2KDVbQe3CQfsbS9kjuOB1rXA+H84N3BuWNAtxaYVBZ8UT6BpfvoCVnZRwfhgwb5Oj1AOvNiXnTjjB+eosz8G2lVmcs8bOs+Ps+IB0ZrywHpR2ErtXCUTGA0Tv2cStnFLrPLDGlav+jaqwjRkljkhFxGNtdihMFNR079HyEeyLP2vl0J1BZIPF783gV0s8ir8ofHW1PsDo3kV2FhXdaZAYbqGLHhZecFCQT8BRJhWd3+zPG8DkVwlow04YG8IXZNZSFzWOC7E4jyPo7n1ASkB8UjCzSjjLWeoSOfu2mivoD1sQUFvOeN5plVRPsiIverXNv53GsB7Y2+/QTtdzDhFSMn7/KR2jb4G6szgLPbvSCsh9lPcN+ghDtafHh5etjxpcvgXx4p1RIknJAYLUFydVJcMdh/4D7hA20V3fbw5tRY7i/PS2Ha+atFhBMDVvF7kDL8seSvvgx9c/kQXPMwIn8YUi9yKen7X2OlH6nft0W4l5XvtiKHjj5vVM7kG4WUTC/1CRsAeuOn1jhPeLCoKgl5tHrZfPuZac4xSPo/XMya8oIVsgEnjVwqqCdaZ0fLHsfA344klNCPtZoX3YqhcnHmkmSaDD34rrQYlmOSWPdOmJn8w="
    - secure: "xvcmxP312BqiB/6m81p7gLBDX2LBNxfU764Q6yShX3G7bRcnXEE3HMW1LPhzTDF55qNFAxLFUV40dkPmsqipXxq/SEL6nI8fVlz5YQXt09WOFK6yFODL9Y5wH8sF9Cri7VARp6hiZHC8JBJipAIO7FCgPlHOGS5XSy0P9SfEgXFg48X1f7gmEi4xEbTKCzW13G3TvOwPg10GHTeDD5qr8BaMTMfHuoWtK/xyuYeOn0Yogy9Jee3cmCVlfDc6kVU0zigTDghBtBCFzfbfylsgjVnEUTT6ds0CWDzt3SW4ZpMiKAQ6PiX3dl7sm1Ju/pdqcXpFIEoKjEFcEoIh89xO5pC4BUL7+bOhEVFJuvuVOYl+XiqNyNQExQ9qi5iLE4zYXSoneEdGE/A+E+f31X6pLy5dmHbe7FCAfbo/T14OVPJIVVEm+BrrJ87zeifA7S3he8b+D5vS9IokHV4wiCosRqK94W0v9TfKJ+rA8pSra9H0Sqa+PZV8EvXxEzIYe+hzQMQzV7rKSk5I4+GCmn8w9xl5FWQVDF3K8OPEINOVassfqPT/Cd/OCzepVkkS1TdeCa+frWB/hpjdtRIzrIg3N/lkb7dZFMaiGR9KIqLi6wa9HzogIANW6RfofDaC31KNmkwk11CGGceX6N8iecEoIR4ICduo7jsX4lcmexIk17I="
    - secure: "NH6s7+bd10GVscFCz26907xj1zeyjMNwGixR8u92ZsxLycFP1sdSjPAnQEO9Fs4JY84YR/VT0fw3MgEdlfkttubIlXQ8n5PhdKK1gCcyRPdfpoRLFUFswpExQS4R+UiYC5kTe6H1K4Tnt+rxw6x9AFfjEdawTygXHwCXYId8DaaTeNy+otDnKb2zkdHyTAN5ysp0P2nZx3lXH/4u/eR9oRnIaVYCjRzcuzNFDMRwJI0JxQ6WEpzOi4xOalQm90tOvKKQ7in2gPc7uKADMiaDCweFx/M/Et/QqcH0gAv/O4eWBPgcQK4hhjJ+WBvrmrqgduUwWYce/j9NM19ctP2X7AAx4F4RlJ4HBDzNeQH7uhaDPxTSnFuMLwuwPsdbAaJbtFdxh37SjoCHB8AzEUM9TquPLaVD8wkQHgYP7XKzAJBPk2Ow4mWH/GBnqo3BQMejZbwTg2c7BplvmT7edAnkzM1i26cNZS7K3GiD5amYFbWTT80Zio9ZIvSnRTzeRXTyPwaRoaXsSDearZPtWWJQgDxVJRuzrF5cO8I3bseB46F/XvmZYV03wOniN366dd2CRjlZmcQNMCTczeIQKJYFF4oyHOsJBg0FHyDipOgEqKfM6PboytT/F6zPuXdSmbKqUWtetk1c+hzX3Mt6OdSUWOJcCLdcNM0V91w7DAVpIRI="
    - REPO=wesovilabs/taurus
    - VERSION=0.0.1
    - TAG=
    - COMMIT=${TRAVIS_COMMIT::8}
    - GLIDE_VERSION=0.12.3
before_script:
  - make clean

install:
  - wget "https://github.com/Masterminds/glide/releases/download/v${GLIDE_VERSION}/glide-v${GLIDE_VERSION}-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v${GLIDE_VERSION}-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"

script:
  - make vet
  - make fmt
  - make lint
  - make check test tests
  - if [[ "$TRAVIS_BRANCH" = /^master$/ ]]; then export TAG="$VERSION"; fi
  - if [[ "$TRAVIS_BRANCH" = /^develop$/ ]]; then export TAG="$VERSION-develop"; fi
  - if [[ "$TRAVIS_BRANCH" = /^feature/.*$/ ]]; then export TAG="$VERSION-feature"; fi

after_success:
  - echo $TAG
  - docker build -t $REPO:$TAG -f Dockerfile .
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

notifications:
  email:
    recipients:
      - developer@wesovilabs.com
    on_success: change
    on_failure: always


