FORMAT: 1A
HOST: http://swatlabstaurus.apiblueprint.org/

# Taurus API

Domains is a simple API allowing teams to vset up their own domains

## Domains Collection [/domains]

### Create a new Domain [POST]

You may create your own domain using this action. It takes a JSON
object containing a domain

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Headers

            Location: /domains/2

    + Body

            {

            }

+ Response 400 (application/json)


+ Response 409 (application/json)



